platform :ios, '9.0'

use_frameworks!
target 'RxSwiftDemo' do

pod 'RxSwift'
pod 'RxCocoa'
pod 'NSObject+Rx'
pod 'Moya/RxSwift'
pod 'ObjectMapper'
pod 'RxDataSources'
pod 'Then'
pod 'Kingfisher'
pod 'SnapKit'
pod 'Reusable'
pod 'MJRefresh'
pod 'SVProgressHUD'

end
