platform :ios, '9.0'

use_frameworks!
target 'RxSwiftDemo' do

pod 'RxSwift'
pod 'RxCocoa'
pod 'NSObject+Rx'
pod 'Moya/RxSwift'
pod 'ObjectMapper', '~> 2.2'
pod 'RxDataSources', '~> 1.0'
pod 'Then'
pod 'Kingfisher', '~> 3.12.1'
pod 'SnapKit', '~> 3.2.0'
pod 'Reusable', '~> 4.0.0'
pod 'MJRefresh'
pod 'SVProgressHUD'

end
